version: '2'
services:
  postgres:
    image: 'kartoza/postgis:latest'
    volumes:
      - ./data/postgre/db:/data/db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=karamelo
  node:
    image: 'node:latest'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - '3333:3333'
    command: 'npm start'
    links:
      - postgres
