version: '3'

services:
  postgres:
    image: 'kartoza/postgis:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=karamelo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
